---
title: "recommender system"
author: "Chi Hang(Philip) Cheung"
date: "2024-11-17"
output: html_document
---
I picked ebay recommender system as my study subject: "https://innovation.ebayinc.com/tech/engineering/building-a-deep-learning-based-retrieval-system-for-personalized-recommendations/"
This system is suitable to be used on both the organization, Ebay, and on the customers.

To customers:
1)Who are your target users?
--The target users are consumers who are interested in buying mostly second hand or new items.

2) What are their key goals?
--The key goal of the ebay system is to provide accurate suggestions that are personalized for the users in this platform. The ebay system is developed as an in-house system.

3) How can you help them accomplish those goals?
--Rather than sololy focusing on providing suggestions that are personalized in categories, i believe the variable of price range is also vial to be part of the algorithm. Typical buyers have a budget/price range in mind when shopping online. With suggestions that are priced similar to the customer's typical spending style, the recommender system could be further personalized to each individual customers. 

To the organization:
1)Who are your target users?
--The target users are Ebay staff.

2) What are their key goals?
--The key goal could be to query items with similar feature and prices that needed to be promot to the front page for quicker sales or to query items that are highly demanded to priced correctly.

3) How can you help them accomplish those goals?
--Similar strategries as the ones mentioned for the customers could be employeed in here. Employees who are tasked for certain sales promotion could benefit from seeing more related item suggestions to reduce manual labor in the analysis aspect.

4) Reverse engineering:
--Ebay attempts to use a Near-Real-Time system to provide instantaneous query speed by utilizing Kafka to capture clicks on the website then relies the input to a deep learning prediction combinedwith Couchbase to create user embeddings. Finally the real-time recommendation application takes user Ids and generates a recommendation result.

5) Improvements:
-- Such system is very quick in processing time but prone to complex architecture in design. The maintenance of such complex system requires a lot of skilled staff and equipments to maintain the serivce. One are of improvement is to prioritize user queries by ranking user tiers. With higher tier, users will be routed to use the NRT system for fast suggestions. Users with lower tier could be routed to using simpler but slower recommendation method. High tiers could be defined as higher likelihood to purchase.